services:
  redis-node-1:
    image: redis-node
    container_name: redis-node-1
    ports:
      - "2221:22"
      - "6379:6379"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      redis-net:
        ipv4_address: 10.10.0.11

  redis-node-2:
    image: redis-node
    container_name: redis-node-2
    ports:
      - "2222:22"
      - "6380:6379"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      redis-net:
        ipv4_address: 10.10.0.12

  redis-node-3:
    image: redis-node
    container_name: redis-node-3
    ports:
      - "2223:22"
      - "6381:6379"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      redis-net:
        ipv4_address: 10.10.0.13

  redis-node-4:
    image: redis-node
    container_name: redis-node-4
    ports:
      - "2224:22"
      - "6382:6379"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      redis-net:
        ipv4_address: 10.10.0.14

  redis-node-5:
    image: redis-node
    container_name: redis-node-5
    ports:
      - "2225:22"
      - "6383:6379"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      redis-net:
        ipv4_address: 10.10.0.15

  redis-node-6:
    image: redis-node
    container_name: redis-node-6
    ports:
      - "2226:22"
      - "6384:6379"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
    networks:
      redis-net:
        ipv4_address: 10.10.0.16

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24